build cpm

diff --git a/bin/cpm b/bin/cpm
--- a/bin/cpm
+++ b/bin/cpm
@@ -9,7 +9,7 @@ GITHUB_DOMAIN=${GITHUB_DOMAIN:-'https://github.com'}
 #!/bin/bash
 #
 
-function is_git_url()
+is_git_url()
 {
     http_regex='(https?)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
     ssh_regex='[-A-Za-z0-9_@/.]+:[-A-Za-z0-9\+&@#/%?=~_|!:,.;]'
@@ -30,7 +30,7 @@ function is_git_url()
 }
 
 # Reads arguments options
-function parse_git_arguments()
+parse_git_arguments()
 {
   # if [ $# -ne 0 ]; then
     TEMP=`getopt -o b::,r:: --long branch::,tag::,workspace-dir::,framework::,repo_url::,config-dir::,cache-dir::,logs-dir::,name::,repo::,team::,composer-update,workspace -n "$0" -- "$@"`
@@ -63,9 +63,13 @@ function parse_git_arguments()
   # fi
 }
 
+git_branch() {
+    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
+}
+
 ##
 ## Retrieve repository name from git url
-function git_repo_name()
+git_repo_name()
 {
   set -e
   if [ $# -ne 1 ]; then
@@ -84,7 +88,7 @@ function git_repo_name()
 # cpm git:clone csimeu/cpm /path/to/save --branch=v1.0 --composer-update --domain=github 
 # cpm git:clone --repo=csimeu/cpm -d /path/to/save
 # cpm git:clone --repo=csimeu/cpm --repo=csimeu/cpm --domain=github 
-function git_clone()
+git_clone()
 {
     set -e
     local _params=
@@ -162,7 +166,7 @@ function git_clone()
 
 # Udapte a git repository branch or tag 
 # usage git_update  --branch=v1.0  </path> --composer-update
-function git_update()
+git_update()
 {
   set -e
   local _path=
@@ -238,7 +242,7 @@ function git_update()
 
 
 # Checks existance of git repository 
-function git_exists()
+git_exists()
 {
     # set -e
     if [ $# -eq 0 ]; then
@@ -557,7 +561,7 @@ if [[ $_ == $0 ]] then
 	install_httpd "$@"
 fi#!/bin/bash
 #
-# Scripts cpm: Cen-R Package Manager
+# Scripts cpm: Csimeu Package Manager
 #
 #   Emploi:     
 #
@@ -566,38 +570,40 @@ fi#!/bin/bash
 
 
 # Stop on first error [duplicate]
-set -e
-
-# source env_vars.sh
-# source cpm_funtions.sh
-# source git.sh
-# source cenr.sh
-# source files.sh
-# source dal.sh
 
 
-if [ $# -eq 0 ]; then
-    # Commande invalide
-    echo "Commande invalide!"
-    exit 1
+_run_cpm() {
+    set -e
+    if [ $# -eq 0 ]; then
+        # Commande invalide
+        echo "Commande invalide!"
+        exit 1
+    fi
+
+    cmd=$1
+
+    case "$cmd" in
+        "cc:dev")
+            shift
+            symfony_cc --env=dev $@
+            exit 0;
+            ;;
+        "cc" | "symfony:cc")
+            shift
+            symfony_cc $@
+            exit 0;
+            ;;
+        *)
+            cmd="${cmd//:/_}" 
+            shift
+            $cmd $@
+        ;;
+    esac
+
+}
+
+## detect if a script is being sourced or not
+if [[ $_ == $0 ]] then
+	_run_cpm "$@"
 fi
 
-cmd=$1
-
-case "$cmd" in
-    "cc:dev")
-        shift
-        symfony_cc --env=dev $@
-        exit 0;
-        ;;
-    "cc" | "symfony:cc")
-        shift
-        symfony_cc $@
-        exit 0;
-        ;;
-    *)
-        cmd="${cmd//:/_}" 
-        shift
-        $cmd $@
-    ;;
-esac
