@update

diff --git a/bin/cpm b/bin/cpm
--- a/bin/cpm
+++ b/bin/cpm
@@ -264,6 +264,70 @@ function servicectl()
 
 }
 
+
+
+# Reads arguments options
+function read_application_arguments()
+{
+    ISDEFAULT=false;
+    IS_SUPERUSER=0
+    local long="help,force,default,superuser,data::,name::,version::,file::,log::,users-config::,config-file::,catalina-home::,install-dir::,port-offset::,config-dir::,data-dir::,home-dir::"
+    long+=",db-name::,db-user::,db-password::,db-host::,db-port::"
+    long+=",realm::,server-url::,server-user::,server-password::,admin-email::,url::,client::,audience::,secret::,login-theme::"
+    long+=",postgresql-version::,postgis-version::"
+    local TEMP=`getopt -o p::,f,h --long $long,password::,user::,email::,host::,port:: -n "$0" -- "$@"`
+
+	eval set -- "$TEMP"         
+    # extract options and their arguments into variables.
+    while true ; do
+        case "$1" in
+            -f|--force) FORCE=1 ; shift 1 ;;
+            --default) IS_DEFAULT=1 ; shift 1 ;;
+            --data) data=${2%"/"} ; shift 2 ;;
+            --data-dir) data_dir=${2%"/"} ; shift 2 ;;
+            --home-dir) home_dir=${2%"/"} ; shift 2 ;;
+            --config-dir) config_dir=${2%"/"} ; shift 2 ;;
+            --name) name=${2} ; shift 2 ;;
+            --file) file=${2}; shift 2 ;;
+            --log) log=${2}; shift 2 ;;
+            --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
+            --version) version=${2:-"$version"}; shift 2 ;;
+            --postgis-version) postgis_version=${2}; shift 2 ;;
+            --postgresql-version) postgresql_version=${2}; shift 2 ;;
+            --catalina-home) catalina_home=${2:-"$catalina_home"}; shift 2 ;;
+            --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
+            --install-dir) INSTALL_DIR=${2:-"$INSTALL_DIR"}; shift 2 ;;
+            --port-offset) port_offset=${2:-"$port_offset"}; shift 2 ;;
+            --port) port=${2:-"$port"}; shift 2 ;;
+            --user) user=${2:-"$user"}; shift 2 ;;
+            --host) host=${2:-"$host"}; shift 2 ;;
+            --password) password=${2:-"$password"}; shift 2 ;;
+            --superuser) IS_SUPERUSER=1 ; shift 1 ;;
+            --db-name) DB_NAME=${2:-"$DB_NAME"}; shift 2 ;;
+            --db-user) DB_USER=${2:-"$DB_USER"}; shift 2 ;;
+            --db-password) DB_PASSWORD=${2:-"$DB_PASSWORD"}; shift 2 ;;
+            --db-host) DB_HOST=${2:-"$DB_HOST"}; shift 2 ;;
+            --db-port) DB_PORT=${2:-"$DB_PORT"}; shift 2 ;;
+            --realm) realm=${2:-"$realm"}; shift 2 ;;
+            --email) email=${2:-"$email"}; shift 2 ;;
+            --url) url=${2:-"$url"}; shift 2 ;;
+            --server-url) server_url=${2:-"$url"}; shift 2 ;;
+            --server-user) server_user=${2}; shift 2 ;;
+            --server-password) server_password=${2}; shift 2 ;;
+            --client) client=${2:-"$client"}; shift 2 ;;
+            --audience) audience=${2:-"$audience"}; shift 2 ;;
+            --secret) secret=${2:-"$secret"}; shift 2 ;;
+            --login-theme) loginTheme=${2:-"$loginTheme"}; shift 2 ;;
+            --) shift ; break ;;
+            *) echo "Internal error! $1" ; exit 1 ;;
+        esac
+    done
+
+    shift $(expr $OPTIND - 1 )
+    _parameters=$@
+    
+  # fi
+}
 #!/bin/bash
 
 
@@ -335,70 +399,6 @@ apache_install() {
 
 }
 
-
-
-# Reads arguments options
-function read_application_arguments()
-{
-    ISDEFAULT=false;
-    IS_SUPERUSER=0
-    local long="help,force,default,superuser,data::,name::,version::,file::,log::,users-config::,config-file::,catalina-home::,install-dir::,port-offset::,config-dir::,data-dir::,home-dir::"
-    long+=",db-name::,db-user::,db-password::,db-host::,db-port::"
-    long+=",realm::,server-url::,server-user::,server-password::,admin-email::,url::,client::,audience::,secret::,login-theme::"
-    long+=",postgresql-version::,postgis-version::"
-    local TEMP=`getopt -o p::,f,h --long $long,password::,user::,email::,host::,port:: -n "$0" -- "$@"`
-
-	eval set -- "$TEMP"         
-    # extract options and their arguments into variables.
-    while true ; do
-        case "$1" in
-            -f|--force) FORCE=1 ; shift 1 ;;
-            --default) IS_DEFAULT=1 ; shift 1 ;;
-            --data) data=${2%"/"} ; shift 2 ;;
-            --data-dir) data_dir=${2%"/"} ; shift 2 ;;
-            --home-dir) home_dir=${2%"/"} ; shift 2 ;;
-            --config-dir) config_dir=${2%"/"} ; shift 2 ;;
-            --name) name=${2} ; shift 2 ;;
-            --file) file=${2}; shift 2 ;;
-            --log) log=${2}; shift 2 ;;
-            --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
-            --version) version=${2:-"$version"}; shift 2 ;;
-            --postgis-version) postgis_version=${2}; shift 2 ;;
-            --postgresql-version) postgresql_version=${2}; shift 2 ;;
-            --catalina-home) catalina_home=${2:-"$catalina_home"}; shift 2 ;;
-            --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
-            --install-dir) INSTALL_DIR=${2:-"$INSTALL_DIR"}; shift 2 ;;
-            --port-offset) port_offset=${2:-"$port_offset"}; shift 2 ;;
-            --port) port=${2:-"$port"}; shift 2 ;;
-            --user) user=${2:-"$user"}; shift 2 ;;
-            --host) host=${2:-"$host"}; shift 2 ;;
-            --password) password=${2:-"$password"}; shift 2 ;;
-            --superuser) IS_SUPERUSER=1 ; shift 1 ;;
-            --db-name) DB_NAME=${2:-"$DB_NAME"}; shift 2 ;;
-            --db-user) DB_USER=${2:-"$DB_USER"}; shift 2 ;;
-            --db-password) DB_PASSWORD=${2:-"$DB_PASSWORD"}; shift 2 ;;
-            --db-host) DB_HOST=${2:-"$DB_HOST"}; shift 2 ;;
-            --db-port) DB_PORT=${2:-"$DB_PORT"}; shift 2 ;;
-            --realm) realm=${2:-"$realm"}; shift 2 ;;
-            --email) email=${2:-"$email"}; shift 2 ;;
-            --url) url=${2:-"$url"}; shift 2 ;;
-            --server-url) server_url=${2:-"$url"}; shift 2 ;;
-            --server-user) server_user=${2}; shift 2 ;;
-            --server-password) server_password=${2}; shift 2 ;;
-            --client) client=${2:-"$client"}; shift 2 ;;
-            --audience) audience=${2:-"$audience"}; shift 2 ;;
-            --secret) secret=${2:-"$secret"}; shift 2 ;;
-            --login-theme) loginTheme=${2:-"$loginTheme"}; shift 2 ;;
-            --) shift ; break ;;
-            *) echo "Internal error! $1" ; exit 1 ;;
-        esac
-    done
-
-    shift $(expr $OPTIND - 1 )
-    _parameters=$@
-    
-  # fi
-}
 #!/bin/bash
 
 # Install blazegraph
@@ -3648,7 +3648,7 @@ function user_add()
     
     if [ ! $(getent group ${username}) ]; then 
         case `plateform` in 
-            alpine) echo "addgroup $gid ${username}" ;;
+            # alpine) echo "addgroup $gid ${username}" ;;
             *) groupadd $gid ${username};;
         esac
     # else
@@ -3658,12 +3658,12 @@ function user_add()
 
     if ! getent passwd ${username} > /dev/null 2>&1; then
         case `plateform` in 
-            alpine) 
-                if [ -n "$home" ]; then home="-h $home"; fi
-                echo "adduser -D --shell /bin/bash $uid $home ${username}"
-                adduser -D --shell /bin/bash  $uid $home ${username}
-                # moduser --shell /bin/bash${username};
-            ;;
+            # alpine) 
+            #     if [ -n "$home" ]; then home="-h $home"; fi
+            #     echo "adduser -D --shell /bin/bash $uid $home ${username}"
+            #     adduser -D --shell /bin/bash  $uid $home ${username}
+            #     # moduser --shell /bin/bash${username};
+            # ;;
             *) 
                 if [ -n "$home" ]; then home="-d $home"; fi
                 useradd --shell /bin/bash $uid -g ${username} $home ${username}
@@ -3682,7 +3682,7 @@ function user_add()
         if ! $(getent group ${group})
         then
             case `plateform` in 
-                alpine) addgroup $group;;
+                # alpine) addgroup $group;;
                 *) groupadd $group;;
             esac
             
@@ -3758,7 +3758,7 @@ function user_update()
         if ! $(getent group ${group})
         then
             case `plateform` in 
-                alpine) addgroup $group;;
+                # alpine) addgroup $group;;
                 *) groupadd $group;;
             esac            
         fi
