@updates

diff --git a/bin/cpm b/bin/cpm
--- a/bin/cpm
+++ b/bin/cpm
@@ -271,75 +271,6 @@ function servicectl()
 
 }
 
-
-
-# Reads arguments options
-function read_application_arguments()
-{
-    ISDEFAULT=false;
-    IS_SUPERUSER=0
-    local long="help,force,drop,default,superuser,data::,name::,version::,file::,log::,users-config::,config-file::,catalina-home::,install-dir::,port-offset::,config-dir::,data-dir::,home-dir::"
-    long+=",db-name::,db-user::,db-password::,db-host::,db-port::"
-    long+=",realm::,server-url::,server-user::,server-password::,admin-email::,url::,client::,audience::,secret::,login-theme::"
-    long+=",postgresql-version::,postgis-version::"
-    long+=",npm-version::,ng-version::,module::"
-    local TEMP=`getopt -o p::,f,h --long $long,password::,user::,email::,host::,port:: -n "$0" -- "$@"`
-
-	eval set -- "$TEMP"         
-    # extract options and their arguments into variables.
-    while true ; do
-        case "$1" in
-            -f|--force) FORCE=1 ; shift 1 ;;
-            --drop) DROP=1 ; shift 1 ;;
-            --default) IS_DEFAULT=1 ; shift 1 ;;
-            --data) data=${2%"/"} ; shift 2 ;;
-            --data-dir) data_dir=${2%"/"} ; shift 2 ;;
-            --home-dir) home_dir=${2%"/"} ; shift 2 ;;
-            --config-dir) config_dir=${2%"/"} ; shift 2 ;;
-            --name) name=${2} ; shift 2 ;;
-            --module) _modules+=" ${2}"; shift 2 ;;
-            --file) file=${2}; shift 2 ;;
-            --log) log=${2}; shift 2 ;;
-            --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
-            --version) version=${2:-"$version"}; shift 2 ;;
-            --npm-version) npm_version=${2:-"$npm_version"}; shift 2 ;;
-            --ng-version) ng_version=${2:-"$ng_version"}; shift 2 ;;
-            --postgis-version) postgis_version=${2}; shift 2 ;;
-            --postgresql-version) postgresql_version=${2}; shift 2 ;;
-            --catalina-home) catalina_home=${2:-"$catalina_home"}; shift 2 ;;
-            --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
-            --install-dir) INSTALL_DIR=${2:-"$INSTALL_DIR"}; shift 2 ;;
-            --port-offset) port_offset=${2:-"$port_offset"}; shift 2 ;;
-            --port) port=${2:-"$port"}; shift 2 ;;
-            --user) user=${2:-"$user"}; shift 2 ;;
-            --host) host=${2:-"$host"}; shift 2 ;;
-            --password) password=${2:-"$password"}; shift 2 ;;
-            --superuser) IS_SUPERUSER=1 ; shift 1 ;;
-            --db-name) DB_NAME=${2:-"$DB_NAME"}; shift 2 ;;
-            --db-user) DB_USER=${2:-"$DB_USER"}; shift 2 ;;
-            --db-password) DB_PASSWORD=${2:-"$DB_PASSWORD"}; shift 2 ;;
-            --db-host) DB_HOST=${2:-"$DB_HOST"}; shift 2 ;;
-            --db-port) DB_PORT=${2:-"$DB_PORT"}; shift 2 ;;
-            --realm) realm=${2:-"$realm"}; shift 2 ;;
-            --email) email=${2:-"$email"}; shift 2 ;;
-            --url) url=${2:-"$url"}; shift 2 ;;
-            --server-url) server_url=${2:-"$url"}; shift 2 ;;
-            --server-user) server_user=${2}; shift 2 ;;
-            --server-password) server_password=${2}; shift 2 ;;
-            --client) client=${2:-"$client"}; shift 2 ;;
-            --audience) audience=${2:-"$audience"}; shift 2 ;;
-            --secret) secret=${2:-"$secret"}; shift 2 ;;
-            --login-theme) loginTheme=${2:-"$loginTheme"}; shift 2 ;;
-            --) shift ; break ;;
-            *) echo "Internal error! $1" ; exit 1 ;;
-        esac
-    done
-
-    shift $(expr $OPTIND - 1 )
-    _parameters=$@
-    
-  # fi
-}
 #!/bin/bash
 
 # Install alertmanager
@@ -553,6 +484,75 @@ apache_install() {
 
 }
 
+
+
+# Reads arguments options
+function read_application_arguments()
+{
+    ISDEFAULT=false;
+    IS_SUPERUSER=0
+    local long="help,force,drop,default,superuser,data::,name::,version::,file::,log::,users-config::,config-file::,catalina-home::,install-dir::,port-offset::,config-dir::,data-dir::,home-dir::"
+    long+=",db-name::,db-user::,db-password::,db-host::,db-port::"
+    long+=",realm::,server-url::,server-user::,server-password::,admin-email::,url::,client::,audience::,secret::,login-theme::"
+    long+=",postgresql-version::,postgis-version::"
+    long+=",npm-version::,ng-version::,module::"
+    local TEMP=`getopt -o p::,f,h --long $long,password::,user::,email::,host::,port:: -n "$0" -- "$@"`
+
+	eval set -- "$TEMP"         
+    # extract options and their arguments into variables.
+    while true ; do
+        case "$1" in
+            -f|--force) FORCE=1 ; shift 1 ;;
+            --drop) DROP=1 ; shift 1 ;;
+            --default) IS_DEFAULT=1 ; shift 1 ;;
+            --data) data=${2%"/"} ; shift 2 ;;
+            --data-dir) data_dir=${2%"/"} ; shift 2 ;;
+            --home-dir) home_dir=${2%"/"} ; shift 2 ;;
+            --config-dir) config_dir=${2%"/"} ; shift 2 ;;
+            --name) name=${2} ; shift 2 ;;
+            --module) _modules+=" ${2}"; shift 2 ;;
+            --file) file=${2}; shift 2 ;;
+            --log) log=${2}; shift 2 ;;
+            --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
+            --version) version=${2:-"$version"}; shift 2 ;;
+            --npm-version) npm_version=${2:-"$npm_version"}; shift 2 ;;
+            --ng-version) ng_version=${2:-"$ng_version"}; shift 2 ;;
+            --postgis-version) postgis_version=${2}; shift 2 ;;
+            --postgresql-version) postgresql_version=${2}; shift 2 ;;
+            --catalina-home) catalina_home=${2:-"$catalina_home"}; shift 2 ;;
+            --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
+            --install-dir) INSTALL_DIR=${2:-"$INSTALL_DIR"}; shift 2 ;;
+            --port-offset) port_offset=${2:-"$port_offset"}; shift 2 ;;
+            --port) port=${2:-"$port"}; shift 2 ;;
+            --user) user=${2:-"$user"}; shift 2 ;;
+            --host) host=${2:-"$host"}; shift 2 ;;
+            --password) password=${2:-"$password"}; shift 2 ;;
+            --superuser) IS_SUPERUSER=1 ; shift 1 ;;
+            --db-name) DB_NAME=${2:-"$DB_NAME"}; shift 2 ;;
+            --db-user) DB_USER=${2:-"$DB_USER"}; shift 2 ;;
+            --db-password) DB_PASSWORD=${2:-"$DB_PASSWORD"}; shift 2 ;;
+            --db-host) DB_HOST=${2:-"$DB_HOST"}; shift 2 ;;
+            --db-port) DB_PORT=${2:-"$DB_PORT"}; shift 2 ;;
+            --realm) realm=${2:-"$realm"}; shift 2 ;;
+            --email) email=${2:-"$email"}; shift 2 ;;
+            --url) url=${2:-"$url"}; shift 2 ;;
+            --server-url) server_url=${2:-"$url"}; shift 2 ;;
+            --server-user) server_user=${2}; shift 2 ;;
+            --server-password) server_password=${2}; shift 2 ;;
+            --client) client=${2:-"$client"}; shift 2 ;;
+            --audience) audience=${2:-"$audience"}; shift 2 ;;
+            --secret) secret=${2:-"$secret"}; shift 2 ;;
+            --login-theme) loginTheme=${2:-"$loginTheme"}; shift 2 ;;
+            --) shift ; break ;;
+            *) echo "Internal error! $1" ; exit 1 ;;
+        esac
+    done
+
+    shift $(expr $OPTIND - 1 )
+    _parameters=$@
+    
+  # fi
+}
 #!/bin/bash
 
 # Install blazegraph
@@ -788,7 +788,7 @@ kibana_install() {
     if [ -n "$_parameters" ]; then set $_parameters; fi
     
     case "$version" in
-        "8") version=8.5.2 ;;
+        "8") version=8 ;;
         *);;
     esac
 
@@ -2136,7 +2136,7 @@ function php_install()
 				;;
 				*)
 					php_exts="$php_exts mysqlnd "
-					pecl_exts="$pecl_exts zip  "
+					pecl_exts="$pecl_exts zip redis  "
 				;;
 			esac
 
@@ -2155,7 +2155,7 @@ function php_install()
 			# for ext in $pecl_exts ; do  cmd+=" php$version-$ext"; done
 			# install php$version  $cmd
 			
-			php_exts="fpm cli mysql pgsql odbc gd imap interbase intl mbstring ldap xml xmlrpc soap pdo curl bcmath opcache zip sqlite3 imagick xdebug apcu"
+			php_exts="fpm cli mysql pgsql odbc gd imap interbase intl mbstring ldap xml xmlrpc soap pdo curl bcmath opcache zip sqlite3 imagick xdebug apcu redis"
 			pecl_exts=
 			case ${version/./} in 
 				5|7) php_exts="$php_exts json  " 
