build

diff --git a/bin/cpm b/bin/cpm
--- a/bin/cpm
+++ b/bin/cpm
@@ -442,7 +442,7 @@ if [[ "$(rpm -E %{rhel})" == "6"  ]];
 then
     sudo chkconfig httpd on
 else 
-    sudo systemctl enable httpd --now
+    sudo systemctl enable httpd
 fi
 
 }
@@ -559,7 +559,6 @@ node_install() {
     fi
 
     npm install -g n && n stable
-    npm install -g grunt-cli @angular/cli sass less
 }
 
 #!/bin/bash
@@ -1359,7 +1358,7 @@ function user_usage()
 function parse_user_arguments()
 {
   # if [ $# -ne 0 ]; then
-    local TEMP=`getopt -o p:: --long help::,uid::,gid::,home::,group:: -n "$0" -- "$@"`
+    local TEMP=`getopt -o p:: --long help::,uid::,gid::,home::,group::,password -n "$0" -- "$@"`
     
 	eval set -- "$TEMP"
     # extract options and their arguments into variables.
@@ -1368,6 +1367,7 @@ function parse_user_arguments()
             --uid) uid="-u ${2}" ; shift 2 ;;
             --gid) gid="-g ${2}" ; shift 2 ;;
             --home) home="-d ${2}" ; shift 2 ;;
+            --password) password="${2}" ; shift 2 ;;
             --group) groups+="${2} "; shift 2 ;;
             --) shift ; break ;;
             *) echo "Internal error! $1" ; exit 1 ;;
@@ -1386,6 +1386,7 @@ function useradd()
     local home=
     local uid=
     local gid=
+    local password=
     local groups=
 
     local _parameters=
@@ -1427,10 +1428,66 @@ function useradd()
         usermod -aG $group ${username}
     done
 
+    if [ -n "$password" ]; then
+        echo "${password}" | passwd $username --stdin 
+    fi
 #     for user in $_USERS
 #     do  
 #     done
 
+}
+
+# 
+function usermod() 
+{
+    set -e
+    local help=0
+    local home=
+    local uid=
+    local gid=
+    local password=
+    local groups=
+
+    local _parameters=
+    parse_user_arguments $@ 
+    if [ -n "$_parameters" ]; then set $_parameters; fi
+
+    username=$1
+
+    if [[ -z "$username" ]]; 
+    then
+        echo "Commande invalide!"
+        echo "    Required username"
+        user_usage
+        exit 1
+    fi
+    
+    if getent passwd ${username} > /dev/null 2>&1; then
+        echo "Commande invalide!"
+        echo "    user '$username' not found"
+        exit 1
+    fi
+
+    if [ -n "$uid" ] ; then
+        usermod $uid ${username};
+    fi
+    if [ -n "$gid" ] ; then
+        usermod $gid ${username};
+    fi
+    
+    for group in $groups
+    do  
+        # checks if user exit
+        if ! $(getent group ${group})
+        then
+            groupadd $group               
+        fi
+        usermod -aG $group ${username}
+    done
+
+    if [ -n "$password" ]; then
+        echo "${password}" | passwd $username --stdin 
+    fi
 }
     
     
