@update

diff --git a/bin/cpm b/bin/cpm
--- a/bin/cpm
+++ b/bin/cpm
@@ -794,13 +794,14 @@ fuseki_install() {
     read_application_arguments $@
     if [ -n "$_parameters" ]; then set $_parameters; fi
 
-    local repo_url=dlcdn.apache.org
-    case "$version" in
-        "4") version=$FUSEKI_DEFAULT_VERSION;;
-        "3") version=3.14.0; repo_url=archive.apache.org/dist ;;
-        *)
-        ;;
-    esac
+    # local repo_url=dlcdn.apache.org
+    local repo_url=archive.apache.org/dist
+    # case "$version" in
+    #     "4") version=$FUSEKI_DEFAULT_VERSION;;
+    #     "3") version=3.14.0; repo_url=archive.apache.org/dist ;;
+    #     *)
+    #     ;;
+    # esac
 
     # local givenname=$name
     name="$appName-$version"
@@ -816,15 +817,15 @@ fuseki_install() {
         exit 1
     fi
 
-    if [ '1' == $FORCE ]; then 
-        sudo rm -rf $INSTALL_DIR/$name $INSTALL_DIR/$appName-$version
-    fi
+    # if [ '1' == $FORCE ]; then 
+    #     sudo rm -rf $INSTALL_DIR/$name $INSTALL_DIR/$appName-$version
+    # fi
     
-    if [ -d $INSTALL_DIR/$name ]
-    then 
-        echo "Application already installed into  $INSTALL_DIR/$name"
-        exit 0
-    fi
+    # if [ -d $INSTALL_DIR/$name ]
+    # then 
+    #     echo "Application already installed into  $INSTALL_DIR/$name"
+    #     exit 0
+    # fi
 
 
     # name=${name//./-/}
@@ -836,6 +837,7 @@ fuseki_install() {
     # local version=3.14.0
     # local install_dir=/usr/share
     # local catalina_home=${CATALINA_HOME:-"/usr/share/tomcat"}
+    # curl -fSL https://$repo_url/jena/binaries/apache-jena-fuseki-$version.war -o ${catalina_home}/webapps/$name.war
 
 
     if [ ! -f /tmp/apache-jena-fuseki-$version.tar.gz ];
@@ -846,34 +848,36 @@ fuseki_install() {
     fi
     
 
-    # curl -fSL https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-$version.tar.gz -o apache-jena-fuseki-$version.tar.gz
-    sudo tar -xzf /tmp/apache-jena-fuseki-$version.tar.gz -C $INSTALL_DIR
-    sudo mv $INSTALL_DIR/apache-jena-fuseki-${version} $INSTALL_DIR/$appName-$version
+    # # curl -fSL https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-$version.tar.gz -o apache-jena-fuseki-$version.tar.gz
+    # sudo tar -xzf /tmp/apache-jena-fuseki-$version.tar.gz -C $INSTALL_DIR
+    # sudo mv $INSTALL_DIR/apache-jena-fuseki-${version} $INSTALL_DIR/$appName-$version
+    sudo tar -xzf /tmp/apache-jena-fuseki-$version.tar.gz
+    # sudo mv /tmp/apache-jena-fuseki-${version} $INSTALL_DIR/$appName-$version
+
+    # # if [ '1' == $IS_DEFAULT ]; then 
+    # #     catalina_home=/usr/share/tomcat; 
+    # #     givename=$_name
+    # #     sudo rm -rf /usr/share/$_name
+    # #     sudo ln -s $INSTALL_DIR/$name /usr/share/$_name
+    # # fi
 
     # if [ '1' == $IS_DEFAULT ]; then 
-    #     catalina_home=/usr/share/tomcat; 
-    #     givename=$_name
-    #     sudo rm -rf /usr/share/$_name
-    #     sudo ln -s $INSTALL_DIR/$name /usr/share/$_name
+    #     # catalina_home=/usr/share/tomcat; 
+    #     # name=$appName
+    #     # sudo rm -rf /usr/share/$appName
+    #     sudo ln -s $INSTALL_DIR/$appName-$version /usr/share/$appName
     # fi
 
-    if [ '1' == $IS_DEFAULT ]; then 
-        # catalina_home=/usr/share/tomcat; 
-        # name=$appName
-        # sudo rm -rf /usr/share/$appName
-        sudo ln -s $INSTALL_DIR/$appName-$version /usr/share/$appName
-    fi
 
-
-    if [ -d $catalina_home/webapps ]; then
-        # if [ '1' == $FORCE ]; then sudo rm -f ${catalina_home}/webapps/${name}.war ; fi
+    # if [ -d $catalina_home/webapps ]; then
+    #     # if [ '1' == $FORCE ]; then sudo rm -f ${catalina_home}/webapps/${name}.war ; fi
         
-        # if [ ! -f ${catalina_home}/webapps/${name}.war ]
-        # then 
-            sudo cp -f "$INSTALL_DIR/${name}/fuseki.war" ${catalina_home}/webapps/$name.war
-        # fi
+    #     # if [ ! -f ${catalina_home}/webapps/${name}.war ]
+    #     # then 
+            sudo cp -f "/tmp/apache-jena-fuseki-${version}/fuseki.war" ${catalina_home}/webapps/$name.war
+    #     # fi
 
-    fi
+    # fi
 
     
 
@@ -2791,43 +2795,43 @@ function solr_install()
 #!/bin/bash
 
 # Install tomcat
-FORCE=0
-IS_DEFAULT=0
-INSTALL_DIR=$INSTALL_DIR
 
-# Reads arguments options
-function parse_tomcat_arguments()
-{
-    # if [ $# -ne 0 ]; then
-    local TEMP=`getopt -o p::,f --long version::,tomcat-config::,users-config::,config-file::,install-dir,force,default -n "$0" -- "$@"`
+# # Reads arguments options
+# function parse_tomcat_arguments()
+# {
+#     # if [ $# -ne 0 ]; then
+#     local TEMP=`getopt -o p::,f --long version::,tomcat-config::,users-config::,config-file::,install-dir,force,default -n "$0" -- "$@"`
       
-    eval set -- "$TEMP"
-    # extract options and their arguments into variables.
-    while true ; do
-        case "$1" in
-            -h|--help) _HELP=1 ; shift 1 ;;
-            -f|--force) FORCE=1 ; shift 1 ;;
-            --default) IS_DEFAULT=1 ; shift 1 ;;
-            --install-dir) INSTALL_DIR=${2%"/"} ; shift 2 ;;
-            --data) data=${2%"/"} ; shift 2 ;;   
-            --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
-            --version) version=${2:-"$version"}; shift 2 ;;
-            # --tomcat-config) tomcat_config=${2:-"$tomcat_config"}; shift 2 ;;
-            --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
-            --) shift ; break ;;
-            *) echo "Internal error! $1" ; exit 1 ;;
-        esac
-    done
+#     eval set -- "$TEMP"
+#     # extract options and their arguments into variables.
+#     while true ; do
+#         case "$1" in
+#             -h|--help) _HELP=1 ; shift 1 ;;
+#             -f|--force) FORCE=1 ; shift 1 ;;
+#             --default) IS_DEFAULT=1 ; shift 1 ;;
+#             --install-dir) INSTALL_DIR=${2%"/"} ; shift 2 ;;
+#             --data) data=${2%"/"} ; shift 2 ;;   
+#             --file-config) config_file=${2:-"$config_file"}; shift 2 ;;
+#             --version) version=${2:-"$version"}; shift 2 ;;
+#             # --tomcat-config) tomcat_config=${2:-"$tomcat_config"}; shift 2 ;;
+#             --users-config) users_config=${2:-"$users_config"}; shift 2 ;;
+#             --) shift ; break ;;
+#             *) echo "Internal error! $1" ; exit 1 ;;
+#         esac
+#     done
 
-    shift $(expr $OPTIND - 1 )
-    _parameters=$@
+#     shift $(expr $OPTIND - 1 )
+#     _parameters=$@
     
-  # fi
-}
+#   # fi
+# }
 
 function tomcat_install() 
 {
 	set -e
+    local FORCE=0
+    local IS_DEFAULT=0
+    local INSTALL_DIR=$INSTALL_DIR
     local appName=tomcat
 	local users_config=
 	local file_config=
@@ -2835,7 +2839,8 @@ function tomcat_install()
 	local version=$TOMCAT_DEFAULT_VERSION
     # echo $@
     local _parameters=
-    parse_tomcat_arguments $@ 
+    # parse_tomcat_arguments $@ 
+    read_application_arguments $@ 
     if [ -n "$_parameters" ]; then set $_parameters; fi
     # data=${data:-"$1"}
     # data=${data:-"."}
